@startuml
class com.evan.seprojrearend.po.SysUserExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.SysUserExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andEmailIsNull()
+ Criteria andEmailIsNotNull()
+ Criteria andEmailEqualTo(String)
+ Criteria andEmailNotEqualTo(String)
+ Criteria andEmailGreaterThan(String)
+ Criteria andEmailGreaterThanOrEqualTo(String)
+ Criteria andEmailLessThan(String)
+ Criteria andEmailLessThanOrEqualTo(String)
+ Criteria andEmailLike(String)
+ Criteria andEmailNotLike(String)
+ Criteria andEmailIn(List<String>)
+ Criteria andEmailNotIn(List<String>)
+ Criteria andEmailBetween(String,String)
+ Criteria andEmailNotBetween(String,String)
+ Criteria andPasswordIsNull()
+ Criteria andPasswordIsNotNull()
+ Criteria andPasswordEqualTo(String)
+ Criteria andPasswordNotEqualTo(String)
+ Criteria andPasswordGreaterThan(String)
+ Criteria andPasswordGreaterThanOrEqualTo(String)
+ Criteria andPasswordLessThan(String)
+ Criteria andPasswordLessThanOrEqualTo(String)
+ Criteria andPasswordLike(String)
+ Criteria andPasswordNotLike(String)
+ Criteria andPasswordIn(List<String>)
+ Criteria andPasswordNotIn(List<String>)
+ Criteria andPasswordBetween(String,String)
+ Criteria andPasswordNotBetween(String,String)
}
class com.evan.seprojrearend.po.SysUserExample.Criteria {
}
class com.evan.seprojrearend.po.SysUserExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.Teacher {
- String name
- String mailAddress
- BigDecimal isBond
- BigDecimal isDeleted
- BigDecimal isResponse
+ String getName()
+ void setName(String)
+ String getMailAddress()
+ void setMailAddress(String)
+ BigDecimal getIsBond()
+ void setIsBond(BigDecimal)
+ BigDecimal getIsDeleted()
+ void setIsDeleted(BigDecimal)
+ BigDecimal getIsResponse()
+ void setIsResponse(BigDecimal)
}
class com.evan.seprojrearend.po.StudentExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.StudentExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andStudentsIdIsNull()
+ Criteria andStudentsIdIsNotNull()
+ Criteria andStudentsIdEqualTo(BigDecimal)
+ Criteria andStudentsIdNotEqualTo(BigDecimal)
+ Criteria andStudentsIdGreaterThan(BigDecimal)
+ Criteria andStudentsIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andStudentsIdLessThan(BigDecimal)
+ Criteria andStudentsIdLessThanOrEqualTo(BigDecimal)
+ Criteria andStudentsIdIn(List<BigDecimal>)
+ Criteria andStudentsIdNotIn(List<BigDecimal>)
+ Criteria andStudentsIdBetween(BigDecimal,BigDecimal)
+ Criteria andStudentsIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andNameIsNull()
+ Criteria andNameIsNotNull()
+ Criteria andNameEqualTo(String)
+ Criteria andNameNotEqualTo(String)
+ Criteria andNameGreaterThan(String)
+ Criteria andNameGreaterThanOrEqualTo(String)
+ Criteria andNameLessThan(String)
+ Criteria andNameLessThanOrEqualTo(String)
+ Criteria andNameLike(String)
+ Criteria andNameNotLike(String)
+ Criteria andNameIn(List<String>)
+ Criteria andNameNotIn(List<String>)
+ Criteria andNameBetween(String,String)
+ Criteria andNameNotBetween(String,String)
+ Criteria andMailAddressIsNull()
+ Criteria andMailAddressIsNotNull()
+ Criteria andMailAddressEqualTo(String)
+ Criteria andMailAddressNotEqualTo(String)
+ Criteria andMailAddressGreaterThan(String)
+ Criteria andMailAddressGreaterThanOrEqualTo(String)
+ Criteria andMailAddressLessThan(String)
+ Criteria andMailAddressLessThanOrEqualTo(String)
+ Criteria andMailAddressLike(String)
+ Criteria andMailAddressNotLike(String)
+ Criteria andMailAddressIn(List<String>)
+ Criteria andMailAddressNotIn(List<String>)
+ Criteria andMailAddressBetween(String,String)
+ Criteria andMailAddressNotBetween(String,String)
+ Criteria andIsBondIsNull()
+ Criteria andIsBondIsNotNull()
+ Criteria andIsBondEqualTo(BigDecimal)
+ Criteria andIsBondNotEqualTo(BigDecimal)
+ Criteria andIsBondGreaterThan(BigDecimal)
+ Criteria andIsBondGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsBondLessThan(BigDecimal)
+ Criteria andIsBondLessThanOrEqualTo(BigDecimal)
+ Criteria andIsBondIn(List<BigDecimal>)
+ Criteria andIsBondNotIn(List<BigDecimal>)
+ Criteria andIsBondBetween(BigDecimal,BigDecimal)
+ Criteria andIsBondNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedIsNull()
+ Criteria andIsDeletedIsNotNull()
+ Criteria andIsDeletedEqualTo(BigDecimal)
+ Criteria andIsDeletedNotEqualTo(BigDecimal)
+ Criteria andIsDeletedGreaterThan(BigDecimal)
+ Criteria andIsDeletedGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedLessThan(BigDecimal)
+ Criteria andIsDeletedLessThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedIn(List<BigDecimal>)
+ Criteria andIsDeletedNotIn(List<BigDecimal>)
+ Criteria andIsDeletedBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsAssistantIsNull()
+ Criteria andIsAssistantIsNotNull()
+ Criteria andIsAssistantEqualTo(BigDecimal)
+ Criteria andIsAssistantNotEqualTo(BigDecimal)
+ Criteria andIsAssistantGreaterThan(BigDecimal)
+ Criteria andIsAssistantGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsAssistantLessThan(BigDecimal)
+ Criteria andIsAssistantLessThanOrEqualTo(BigDecimal)
+ Criteria andIsAssistantIn(List<BigDecimal>)
+ Criteria andIsAssistantNotIn(List<BigDecimal>)
+ Criteria andIsAssistantBetween(BigDecimal,BigDecimal)
+ Criteria andIsAssistantNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.StudentExample.Criteria {
}
class com.evan.seprojrearend.po.StudentExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.CourSectionKey {
- BigDecimal sectionId
- BigDecimal schoolId
+ BigDecimal getSectionId()
+ void setSectionId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.School {
- BigDecimal schoolId
- String schoolName
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
+ String getSchoolName()
+ void setSchoolName(String)
}
class com.evan.seprojrearend.po.CourseKey {
- BigDecimal courseId
- BigDecimal schoolId
+ BigDecimal getCourseId()
+ void setCourseId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.ReportsExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.ReportsExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andExperimentIdIsNull()
+ Criteria andExperimentIdIsNotNull()
+ Criteria andExperimentIdEqualTo(BigDecimal)
+ Criteria andExperimentIdNotEqualTo(BigDecimal)
+ Criteria andExperimentIdGreaterThan(BigDecimal)
+ Criteria andExperimentIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andExperimentIdLessThan(BigDecimal)
+ Criteria andExperimentIdLessThanOrEqualTo(BigDecimal)
+ Criteria andExperimentIdIn(List<BigDecimal>)
+ Criteria andExperimentIdNotIn(List<BigDecimal>)
+ Criteria andExperimentIdBetween(BigDecimal,BigDecimal)
+ Criteria andExperimentIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andStudentIdIsNull()
+ Criteria andStudentIdIsNotNull()
+ Criteria andStudentIdEqualTo(BigDecimal)
+ Criteria andStudentIdNotEqualTo(BigDecimal)
+ Criteria andStudentIdGreaterThan(BigDecimal)
+ Criteria andStudentIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andStudentIdLessThan(BigDecimal)
+ Criteria andStudentIdLessThanOrEqualTo(BigDecimal)
+ Criteria andStudentIdIn(List<BigDecimal>)
+ Criteria andStudentIdNotIn(List<BigDecimal>)
+ Criteria andStudentIdBetween(BigDecimal,BigDecimal)
+ Criteria andStudentIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andFinDataIsNull()
+ Criteria andFinDataIsNotNull()
+ Criteria andFinDataEqualTo(Date)
+ Criteria andFinDataNotEqualTo(Date)
+ Criteria andFinDataGreaterThan(Date)
+ Criteria andFinDataGreaterThanOrEqualTo(Date)
+ Criteria andFinDataLessThan(Date)
+ Criteria andFinDataLessThanOrEqualTo(Date)
+ Criteria andFinDataIn(List<Date>)
+ Criteria andFinDataNotIn(List<Date>)
+ Criteria andFinDataBetween(Date,Date)
+ Criteria andFinDataNotBetween(Date,Date)
+ Criteria andMarkIsNull()
+ Criteria andMarkIsNotNull()
+ Criteria andMarkEqualTo(BigDecimal)
+ Criteria andMarkNotEqualTo(BigDecimal)
+ Criteria andMarkGreaterThan(BigDecimal)
+ Criteria andMarkGreaterThanOrEqualTo(BigDecimal)
+ Criteria andMarkLessThan(BigDecimal)
+ Criteria andMarkLessThanOrEqualTo(BigDecimal)
+ Criteria andMarkIn(List<BigDecimal>)
+ Criteria andMarkNotIn(List<BigDecimal>)
+ Criteria andMarkBetween(BigDecimal,BigDecimal)
+ Criteria andMarkNotBetween(BigDecimal,BigDecimal)
+ Criteria andReportAddressIsNull()
+ Criteria andReportAddressIsNotNull()
+ Criteria andReportAddressEqualTo(String)
+ Criteria andReportAddressNotEqualTo(String)
+ Criteria andReportAddressGreaterThan(String)
+ Criteria andReportAddressGreaterThanOrEqualTo(String)
+ Criteria andReportAddressLessThan(String)
+ Criteria andReportAddressLessThanOrEqualTo(String)
+ Criteria andReportAddressLike(String)
+ Criteria andReportAddressNotLike(String)
+ Criteria andReportAddressIn(List<String>)
+ Criteria andReportAddressNotIn(List<String>)
+ Criteria andReportAddressBetween(String,String)
+ Criteria andReportAddressNotBetween(String,String)
+ Criteria andTeacherIdIsNull()
+ Criteria andTeacherIdIsNotNull()
+ Criteria andTeacherIdEqualTo(BigDecimal)
+ Criteria andTeacherIdNotEqualTo(BigDecimal)
+ Criteria andTeacherIdGreaterThan(BigDecimal)
+ Criteria andTeacherIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdLessThan(BigDecimal)
+ Criteria andTeacherIdLessThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdIn(List<BigDecimal>)
+ Criteria andTeacherIdNotIn(List<BigDecimal>)
+ Criteria andTeacherIdBetween(BigDecimal,BigDecimal)
+ Criteria andTeacherIdNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.ReportsExample.Criteria {
}
class com.evan.seprojrearend.po.ReportsExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.ScoreInfoKey {
- BigDecimal sectionId
- BigDecimal studentId
- BigDecimal schoolId
+ BigDecimal getSectionId()
+ void setSectionId(BigDecimal)
+ BigDecimal getStudentId()
+ void setStudentId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.Literature {
- String autoIncrementName
- BigDecimal experimentId
- BigDecimal mark
- String litertureAddress
+ String getAutoIncrementName()
+ void setAutoIncrementName(String)
+ BigDecimal getExperimentId()
+ void setExperimentId(BigDecimal)
+ BigDecimal getMark()
+ void setMark(BigDecimal)
+ String getLitertureAddress()
+ void setLitertureAddress(String)
}
class com.evan.seprojrearend.po.SectionMessageKey {
- BigDecimal sectionId
- BigDecimal mesId
- BigDecimal schoolId
+ BigDecimal getSectionId()
+ void setSectionId(BigDecimal)
+ BigDecimal getMesId()
+ void setMesId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.ExperimentKey {
- BigDecimal experimentId
- BigDecimal schoolId
+ BigDecimal getExperimentId()
+ void setExperimentId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.Administrator {
- String name
- String mailAddress
- BigDecimal isBond
- BigDecimal isDeleted
+ String getName()
+ void setName(String)
+ String getMailAddress()
+ void setMailAddress(String)
+ BigDecimal getIsBond()
+ void setIsBond(BigDecimal)
+ BigDecimal getIsDeleted()
+ void setIsDeleted(BigDecimal)
}
class com.evan.seprojrearend.po.SectionInfoKey {
- BigDecimal sectionId
- BigDecimal studentId
- BigDecimal schoolId
+ BigDecimal getSectionId()
+ void setSectionId(BigDecimal)
+ BigDecimal getStudentId()
+ void setStudentId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.Experiment {
- String experimentName
- BigDecimal sectionId
- BigDecimal teacherId
- BigDecimal isDeleted
- String experimentContext
+ String getExperimentName()
+ void setExperimentName(String)
+ BigDecimal getSectionId()
+ void setSectionId(BigDecimal)
+ BigDecimal getTeacherId()
+ void setTeacherId(BigDecimal)
+ BigDecimal getIsDeleted()
+ void setIsDeleted(BigDecimal)
+ String getExperimentContext()
+ void setExperimentContext(String)
}
class com.evan.seprojrearend.po.AdministratorKey {
- BigDecimal adId
- BigDecimal schoolId
+ BigDecimal getAdId()
+ void setAdId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.CourSection {
- BigDecimal teacherId
- BigDecimal courseId
- String sectionTime
- BigDecimal isComplete
- String message
+ BigDecimal getTeacherId()
+ void setTeacherId(BigDecimal)
+ BigDecimal getCourseId()
+ void setCourseId(BigDecimal)
+ String getSectionTime()
+ void setSectionTime(String)
+ BigDecimal getIsComplete()
+ void setIsComplete(BigDecimal)
+ String getMessage()
+ void setMessage(String)
}
class com.evan.seprojrearend.po.Course {
- String courseName
- BigDecimal resTeacherId
- BigDecimal isDeleted
+ String getCourseName()
+ void setCourseName(String)
+ BigDecimal getResTeacherId()
+ void setResTeacherId(BigDecimal)
+ BigDecimal getIsDeleted()
+ void setIsDeleted(BigDecimal)
}
class com.evan.seprojrearend.po.LiteratureExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.LiteratureExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andLiteratureIdIsNull()
+ Criteria andLiteratureIdIsNotNull()
+ Criteria andLiteratureIdEqualTo(BigDecimal)
+ Criteria andLiteratureIdNotEqualTo(BigDecimal)
+ Criteria andLiteratureIdGreaterThan(BigDecimal)
+ Criteria andLiteratureIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andLiteratureIdLessThan(BigDecimal)
+ Criteria andLiteratureIdLessThanOrEqualTo(BigDecimal)
+ Criteria andLiteratureIdIn(List<BigDecimal>)
+ Criteria andLiteratureIdNotIn(List<BigDecimal>)
+ Criteria andLiteratureIdBetween(BigDecimal,BigDecimal)
+ Criteria andLiteratureIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andAutoIncrementNameIsNull()
+ Criteria andAutoIncrementNameIsNotNull()
+ Criteria andAutoIncrementNameEqualTo(String)
+ Criteria andAutoIncrementNameNotEqualTo(String)
+ Criteria andAutoIncrementNameGreaterThan(String)
+ Criteria andAutoIncrementNameGreaterThanOrEqualTo(String)
+ Criteria andAutoIncrementNameLessThan(String)
+ Criteria andAutoIncrementNameLessThanOrEqualTo(String)
+ Criteria andAutoIncrementNameLike(String)
+ Criteria andAutoIncrementNameNotLike(String)
+ Criteria andAutoIncrementNameIn(List<String>)
+ Criteria andAutoIncrementNameNotIn(List<String>)
+ Criteria andAutoIncrementNameBetween(String,String)
+ Criteria andAutoIncrementNameNotBetween(String,String)
+ Criteria andExperimentIdIsNull()
+ Criteria andExperimentIdIsNotNull()
+ Criteria andExperimentIdEqualTo(BigDecimal)
+ Criteria andExperimentIdNotEqualTo(BigDecimal)
+ Criteria andExperimentIdGreaterThan(BigDecimal)
+ Criteria andExperimentIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andExperimentIdLessThan(BigDecimal)
+ Criteria andExperimentIdLessThanOrEqualTo(BigDecimal)
+ Criteria andExperimentIdIn(List<BigDecimal>)
+ Criteria andExperimentIdNotIn(List<BigDecimal>)
+ Criteria andExperimentIdBetween(BigDecimal,BigDecimal)
+ Criteria andExperimentIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andMarkIsNull()
+ Criteria andMarkIsNotNull()
+ Criteria andMarkEqualTo(BigDecimal)
+ Criteria andMarkNotEqualTo(BigDecimal)
+ Criteria andMarkGreaterThan(BigDecimal)
+ Criteria andMarkGreaterThanOrEqualTo(BigDecimal)
+ Criteria andMarkLessThan(BigDecimal)
+ Criteria andMarkLessThanOrEqualTo(BigDecimal)
+ Criteria andMarkIn(List<BigDecimal>)
+ Criteria andMarkNotIn(List<BigDecimal>)
+ Criteria andMarkBetween(BigDecimal,BigDecimal)
+ Criteria andMarkNotBetween(BigDecimal,BigDecimal)
+ Criteria andLitertureAddressIsNull()
+ Criteria andLitertureAddressIsNotNull()
+ Criteria andLitertureAddressEqualTo(String)
+ Criteria andLitertureAddressNotEqualTo(String)
+ Criteria andLitertureAddressGreaterThan(String)
+ Criteria andLitertureAddressGreaterThanOrEqualTo(String)
+ Criteria andLitertureAddressLessThan(String)
+ Criteria andLitertureAddressLessThanOrEqualTo(String)
+ Criteria andLitertureAddressLike(String)
+ Criteria andLitertureAddressNotLike(String)
+ Criteria andLitertureAddressIn(List<String>)
+ Criteria andLitertureAddressNotIn(List<String>)
+ Criteria andLitertureAddressBetween(String,String)
+ Criteria andLitertureAddressNotBetween(String,String)
}
class com.evan.seprojrearend.po.LiteratureExample.Criteria {
}
class com.evan.seprojrearend.po.LiteratureExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.SysSchoolMesExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.SysSchoolMesExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andEmailIsNull()
+ Criteria andEmailIsNotNull()
+ Criteria andEmailEqualTo(String)
+ Criteria andEmailNotEqualTo(String)
+ Criteria andEmailGreaterThan(String)
+ Criteria andEmailGreaterThanOrEqualTo(String)
+ Criteria andEmailLessThan(String)
+ Criteria andEmailLessThanOrEqualTo(String)
+ Criteria andEmailLike(String)
+ Criteria andEmailNotLike(String)
+ Criteria andEmailIn(List<String>)
+ Criteria andEmailNotIn(List<String>)
+ Criteria andEmailBetween(String,String)
+ Criteria andEmailNotBetween(String,String)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.SysSchoolMesExample.Criteria {
}
class com.evan.seprojrearend.po.SysSchoolMesExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.TeacherKey {
- BigDecimal teacherId
- BigDecimal schoolId
+ BigDecimal getTeacherId()
+ void setTeacherId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.ExperimentExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.ExperimentExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andExperimentIdIsNull()
+ Criteria andExperimentIdIsNotNull()
+ Criteria andExperimentIdEqualTo(BigDecimal)
+ Criteria andExperimentIdNotEqualTo(BigDecimal)
+ Criteria andExperimentIdGreaterThan(BigDecimal)
+ Criteria andExperimentIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andExperimentIdLessThan(BigDecimal)
+ Criteria andExperimentIdLessThanOrEqualTo(BigDecimal)
+ Criteria andExperimentIdIn(List<BigDecimal>)
+ Criteria andExperimentIdNotIn(List<BigDecimal>)
+ Criteria andExperimentIdBetween(BigDecimal,BigDecimal)
+ Criteria andExperimentIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andExperimentNameIsNull()
+ Criteria andExperimentNameIsNotNull()
+ Criteria andExperimentNameEqualTo(String)
+ Criteria andExperimentNameNotEqualTo(String)
+ Criteria andExperimentNameGreaterThan(String)
+ Criteria andExperimentNameGreaterThanOrEqualTo(String)
+ Criteria andExperimentNameLessThan(String)
+ Criteria andExperimentNameLessThanOrEqualTo(String)
+ Criteria andExperimentNameLike(String)
+ Criteria andExperimentNameNotLike(String)
+ Criteria andExperimentNameIn(List<String>)
+ Criteria andExperimentNameNotIn(List<String>)
+ Criteria andExperimentNameBetween(String,String)
+ Criteria andExperimentNameNotBetween(String,String)
+ Criteria andSectionIdIsNull()
+ Criteria andSectionIdIsNotNull()
+ Criteria andSectionIdEqualTo(BigDecimal)
+ Criteria andSectionIdNotEqualTo(BigDecimal)
+ Criteria andSectionIdGreaterThan(BigDecimal)
+ Criteria andSectionIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdLessThan(BigDecimal)
+ Criteria andSectionIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdIn(List<BigDecimal>)
+ Criteria andSectionIdNotIn(List<BigDecimal>)
+ Criteria andSectionIdBetween(BigDecimal,BigDecimal)
+ Criteria andSectionIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andTeacherIdIsNull()
+ Criteria andTeacherIdIsNotNull()
+ Criteria andTeacherIdEqualTo(BigDecimal)
+ Criteria andTeacherIdNotEqualTo(BigDecimal)
+ Criteria andTeacherIdGreaterThan(BigDecimal)
+ Criteria andTeacherIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdLessThan(BigDecimal)
+ Criteria andTeacherIdLessThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdIn(List<BigDecimal>)
+ Criteria andTeacherIdNotIn(List<BigDecimal>)
+ Criteria andTeacherIdBetween(BigDecimal,BigDecimal)
+ Criteria andTeacherIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedIsNull()
+ Criteria andIsDeletedIsNotNull()
+ Criteria andIsDeletedEqualTo(BigDecimal)
+ Criteria andIsDeletedNotEqualTo(BigDecimal)
+ Criteria andIsDeletedGreaterThan(BigDecimal)
+ Criteria andIsDeletedGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedLessThan(BigDecimal)
+ Criteria andIsDeletedLessThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedIn(List<BigDecimal>)
+ Criteria andIsDeletedNotIn(List<BigDecimal>)
+ Criteria andIsDeletedBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.ExperimentExample.Criteria {
}
class com.evan.seprojrearend.po.ExperimentExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.SchoolExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.SchoolExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolNameIsNull()
+ Criteria andSchoolNameIsNotNull()
+ Criteria andSchoolNameEqualTo(String)
+ Criteria andSchoolNameNotEqualTo(String)
+ Criteria andSchoolNameGreaterThan(String)
+ Criteria andSchoolNameGreaterThanOrEqualTo(String)
+ Criteria andSchoolNameLessThan(String)
+ Criteria andSchoolNameLessThanOrEqualTo(String)
+ Criteria andSchoolNameLike(String)
+ Criteria andSchoolNameNotLike(String)
+ Criteria andSchoolNameIn(List<String>)
+ Criteria andSchoolNameNotIn(List<String>)
+ Criteria andSchoolNameBetween(String,String)
+ Criteria andSchoolNameNotBetween(String,String)
}
class com.evan.seprojrearend.po.SchoolExample.Criteria {
}
class com.evan.seprojrearend.po.SchoolExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.Reports {
- Date finData
- BigDecimal mark
- String reportAddress
- BigDecimal teacherId
+ Date getFinData()
+ void setFinData(Date)
+ BigDecimal getMark()
+ void setMark(BigDecimal)
+ String getReportAddress()
+ void setReportAddress(String)
+ BigDecimal getTeacherId()
+ void setTeacherId(BigDecimal)
}
class com.evan.seprojrearend.po.TeacherExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.TeacherExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andTeacherIdIsNull()
+ Criteria andTeacherIdIsNotNull()
+ Criteria andTeacherIdEqualTo(BigDecimal)
+ Criteria andTeacherIdNotEqualTo(BigDecimal)
+ Criteria andTeacherIdGreaterThan(BigDecimal)
+ Criteria andTeacherIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdLessThan(BigDecimal)
+ Criteria andTeacherIdLessThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdIn(List<BigDecimal>)
+ Criteria andTeacherIdNotIn(List<BigDecimal>)
+ Criteria andTeacherIdBetween(BigDecimal,BigDecimal)
+ Criteria andTeacherIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andNameIsNull()
+ Criteria andNameIsNotNull()
+ Criteria andNameEqualTo(String)
+ Criteria andNameNotEqualTo(String)
+ Criteria andNameGreaterThan(String)
+ Criteria andNameGreaterThanOrEqualTo(String)
+ Criteria andNameLessThan(String)
+ Criteria andNameLessThanOrEqualTo(String)
+ Criteria andNameLike(String)
+ Criteria andNameNotLike(String)
+ Criteria andNameIn(List<String>)
+ Criteria andNameNotIn(List<String>)
+ Criteria andNameBetween(String,String)
+ Criteria andNameNotBetween(String,String)
+ Criteria andMailAddressIsNull()
+ Criteria andMailAddressIsNotNull()
+ Criteria andMailAddressEqualTo(String)
+ Criteria andMailAddressNotEqualTo(String)
+ Criteria andMailAddressGreaterThan(String)
+ Criteria andMailAddressGreaterThanOrEqualTo(String)
+ Criteria andMailAddressLessThan(String)
+ Criteria andMailAddressLessThanOrEqualTo(String)
+ Criteria andMailAddressLike(String)
+ Criteria andMailAddressNotLike(String)
+ Criteria andMailAddressIn(List<String>)
+ Criteria andMailAddressNotIn(List<String>)
+ Criteria andMailAddressBetween(String,String)
+ Criteria andMailAddressNotBetween(String,String)
+ Criteria andIsBondIsNull()
+ Criteria andIsBondIsNotNull()
+ Criteria andIsBondEqualTo(BigDecimal)
+ Criteria andIsBondNotEqualTo(BigDecimal)
+ Criteria andIsBondGreaterThan(BigDecimal)
+ Criteria andIsBondGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsBondLessThan(BigDecimal)
+ Criteria andIsBondLessThanOrEqualTo(BigDecimal)
+ Criteria andIsBondIn(List<BigDecimal>)
+ Criteria andIsBondNotIn(List<BigDecimal>)
+ Criteria andIsBondBetween(BigDecimal,BigDecimal)
+ Criteria andIsBondNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedIsNull()
+ Criteria andIsDeletedIsNotNull()
+ Criteria andIsDeletedEqualTo(BigDecimal)
+ Criteria andIsDeletedNotEqualTo(BigDecimal)
+ Criteria andIsDeletedGreaterThan(BigDecimal)
+ Criteria andIsDeletedGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedLessThan(BigDecimal)
+ Criteria andIsDeletedLessThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedIn(List<BigDecimal>)
+ Criteria andIsDeletedNotIn(List<BigDecimal>)
+ Criteria andIsDeletedBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsResponseIsNull()
+ Criteria andIsResponseIsNotNull()
+ Criteria andIsResponseEqualTo(BigDecimal)
+ Criteria andIsResponseNotEqualTo(BigDecimal)
+ Criteria andIsResponseGreaterThan(BigDecimal)
+ Criteria andIsResponseGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsResponseLessThan(BigDecimal)
+ Criteria andIsResponseLessThanOrEqualTo(BigDecimal)
+ Criteria andIsResponseIn(List<BigDecimal>)
+ Criteria andIsResponseNotIn(List<BigDecimal>)
+ Criteria andIsResponseBetween(BigDecimal,BigDecimal)
+ Criteria andIsResponseNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.TeacherExample.Criteria {
}
class com.evan.seprojrearend.po.TeacherExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.ScoreInfoExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.ScoreInfoExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andSectionIdIsNull()
+ Criteria andSectionIdIsNotNull()
+ Criteria andSectionIdEqualTo(BigDecimal)
+ Criteria andSectionIdNotEqualTo(BigDecimal)
+ Criteria andSectionIdGreaterThan(BigDecimal)
+ Criteria andSectionIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdLessThan(BigDecimal)
+ Criteria andSectionIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdIn(List<BigDecimal>)
+ Criteria andSectionIdNotIn(List<BigDecimal>)
+ Criteria andSectionIdBetween(BigDecimal,BigDecimal)
+ Criteria andSectionIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andStudentIdIsNull()
+ Criteria andStudentIdIsNotNull()
+ Criteria andStudentIdEqualTo(BigDecimal)
+ Criteria andStudentIdNotEqualTo(BigDecimal)
+ Criteria andStudentIdGreaterThan(BigDecimal)
+ Criteria andStudentIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andStudentIdLessThan(BigDecimal)
+ Criteria andStudentIdLessThanOrEqualTo(BigDecimal)
+ Criteria andStudentIdIn(List<BigDecimal>)
+ Criteria andStudentIdNotIn(List<BigDecimal>)
+ Criteria andStudentIdBetween(BigDecimal,BigDecimal)
+ Criteria andStudentIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andScoreIsNull()
+ Criteria andScoreIsNotNull()
+ Criteria andScoreEqualTo(BigDecimal)
+ Criteria andScoreNotEqualTo(BigDecimal)
+ Criteria andScoreGreaterThan(BigDecimal)
+ Criteria andScoreGreaterThanOrEqualTo(BigDecimal)
+ Criteria andScoreLessThan(BigDecimal)
+ Criteria andScoreLessThanOrEqualTo(BigDecimal)
+ Criteria andScoreIn(List<BigDecimal>)
+ Criteria andScoreNotIn(List<BigDecimal>)
+ Criteria andScoreBetween(BigDecimal,BigDecimal)
+ Criteria andScoreNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedIsNull()
+ Criteria andIsDeletedIsNotNull()
+ Criteria andIsDeletedEqualTo(BigDecimal)
+ Criteria andIsDeletedNotEqualTo(BigDecimal)
+ Criteria andIsDeletedGreaterThan(BigDecimal)
+ Criteria andIsDeletedGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedLessThan(BigDecimal)
+ Criteria andIsDeletedLessThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedIn(List<BigDecimal>)
+ Criteria andIsDeletedNotIn(List<BigDecimal>)
+ Criteria andIsDeletedBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.ScoreInfoExample.Criteria {
}
class com.evan.seprojrearend.po.ScoreInfoExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.SectionInfo {
- BigDecimal isDeleted
+ BigDecimal getIsDeleted()
+ void setIsDeleted(BigDecimal)
}
class com.evan.seprojrearend.po.ScoreInfo {
- BigDecimal score
- BigDecimal isDeleted
+ BigDecimal getScore()
+ void setScore(BigDecimal)
+ BigDecimal getIsDeleted()
+ void setIsDeleted(BigDecimal)
}
class com.evan.seprojrearend.po.SectionMessageExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.SectionMessageExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andSectionIdIsNull()
+ Criteria andSectionIdIsNotNull()
+ Criteria andSectionIdEqualTo(BigDecimal)
+ Criteria andSectionIdNotEqualTo(BigDecimal)
+ Criteria andSectionIdGreaterThan(BigDecimal)
+ Criteria andSectionIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdLessThan(BigDecimal)
+ Criteria andSectionIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdIn(List<BigDecimal>)
+ Criteria andSectionIdNotIn(List<BigDecimal>)
+ Criteria andSectionIdBetween(BigDecimal,BigDecimal)
+ Criteria andSectionIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andMesIdIsNull()
+ Criteria andMesIdIsNotNull()
+ Criteria andMesIdEqualTo(BigDecimal)
+ Criteria andMesIdNotEqualTo(BigDecimal)
+ Criteria andMesIdGreaterThan(BigDecimal)
+ Criteria andMesIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andMesIdLessThan(BigDecimal)
+ Criteria andMesIdLessThanOrEqualTo(BigDecimal)
+ Criteria andMesIdIn(List<BigDecimal>)
+ Criteria andMesIdNotIn(List<BigDecimal>)
+ Criteria andMesIdBetween(BigDecimal,BigDecimal)
+ Criteria andMesIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.SectionMessageExample.Criteria {
}
class com.evan.seprojrearend.po.SectionMessageExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.CourseExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.CourseExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andCourseIdIsNull()
+ Criteria andCourseIdIsNotNull()
+ Criteria andCourseIdEqualTo(BigDecimal)
+ Criteria andCourseIdNotEqualTo(BigDecimal)
+ Criteria andCourseIdGreaterThan(BigDecimal)
+ Criteria andCourseIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andCourseIdLessThan(BigDecimal)
+ Criteria andCourseIdLessThanOrEqualTo(BigDecimal)
+ Criteria andCourseIdIn(List<BigDecimal>)
+ Criteria andCourseIdNotIn(List<BigDecimal>)
+ Criteria andCourseIdBetween(BigDecimal,BigDecimal)
+ Criteria andCourseIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andCourseNameIsNull()
+ Criteria andCourseNameIsNotNull()
+ Criteria andCourseNameEqualTo(String)
+ Criteria andCourseNameNotEqualTo(String)
+ Criteria andCourseNameGreaterThan(String)
+ Criteria andCourseNameGreaterThanOrEqualTo(String)
+ Criteria andCourseNameLessThan(String)
+ Criteria andCourseNameLessThanOrEqualTo(String)
+ Criteria andCourseNameLike(String)
+ Criteria andCourseNameNotLike(String)
+ Criteria andCourseNameIn(List<String>)
+ Criteria andCourseNameNotIn(List<String>)
+ Criteria andCourseNameBetween(String,String)
+ Criteria andCourseNameNotBetween(String,String)
+ Criteria andResTeacherIdIsNull()
+ Criteria andResTeacherIdIsNotNull()
+ Criteria andResTeacherIdEqualTo(BigDecimal)
+ Criteria andResTeacherIdNotEqualTo(BigDecimal)
+ Criteria andResTeacherIdGreaterThan(BigDecimal)
+ Criteria andResTeacherIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andResTeacherIdLessThan(BigDecimal)
+ Criteria andResTeacherIdLessThanOrEqualTo(BigDecimal)
+ Criteria andResTeacherIdIn(List<BigDecimal>)
+ Criteria andResTeacherIdNotIn(List<BigDecimal>)
+ Criteria andResTeacherIdBetween(BigDecimal,BigDecimal)
+ Criteria andResTeacherIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedIsNull()
+ Criteria andIsDeletedIsNotNull()
+ Criteria andIsDeletedEqualTo(BigDecimal)
+ Criteria andIsDeletedNotEqualTo(BigDecimal)
+ Criteria andIsDeletedGreaterThan(BigDecimal)
+ Criteria andIsDeletedGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedLessThan(BigDecimal)
+ Criteria andIsDeletedLessThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedIn(List<BigDecimal>)
+ Criteria andIsDeletedNotIn(List<BigDecimal>)
+ Criteria andIsDeletedBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.CourseExample.Criteria {
}
class com.evan.seprojrearend.po.CourseExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.SysUser {
- String email
- String password
+ String getEmail()
+ void setEmail(String)
+ String getPassword()
+ void setPassword(String)
}
class com.evan.seprojrearend.po.ReportsKey {
- BigDecimal experimentId
- BigDecimal studentId
- BigDecimal schoolId
+ BigDecimal getExperimentId()
+ void setExperimentId(BigDecimal)
+ BigDecimal getStudentId()
+ void setStudentId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.LiteratureKey {
- BigDecimal literatureId
- BigDecimal schoolId
+ BigDecimal getLiteratureId()
+ void setLiteratureId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.Student {
- String name
- String mailAddress
- BigDecimal isBond
- BigDecimal isDeleted
- BigDecimal isAssistant
+ String getName()
+ void setName(String)
+ String getMailAddress()
+ void setMailAddress(String)
+ BigDecimal getIsBond()
+ void setIsBond(BigDecimal)
+ BigDecimal getIsDeleted()
+ void setIsDeleted(BigDecimal)
+ BigDecimal getIsAssistant()
+ void setIsAssistant(BigDecimal)
}
class com.evan.seprojrearend.po.StudentKey {
- BigDecimal studentsId
- BigDecimal schoolId
+ BigDecimal getStudentsId()
+ void setStudentsId(BigDecimal)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}
class com.evan.seprojrearend.po.AdministratorExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.AdministratorExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andAdIdIsNull()
+ Criteria andAdIdIsNotNull()
+ Criteria andAdIdEqualTo(BigDecimal)
+ Criteria andAdIdNotEqualTo(BigDecimal)
+ Criteria andAdIdGreaterThan(BigDecimal)
+ Criteria andAdIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andAdIdLessThan(BigDecimal)
+ Criteria andAdIdLessThanOrEqualTo(BigDecimal)
+ Criteria andAdIdIn(List<BigDecimal>)
+ Criteria andAdIdNotIn(List<BigDecimal>)
+ Criteria andAdIdBetween(BigDecimal,BigDecimal)
+ Criteria andAdIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andNameIsNull()
+ Criteria andNameIsNotNull()
+ Criteria andNameEqualTo(String)
+ Criteria andNameNotEqualTo(String)
+ Criteria andNameGreaterThan(String)
+ Criteria andNameGreaterThanOrEqualTo(String)
+ Criteria andNameLessThan(String)
+ Criteria andNameLessThanOrEqualTo(String)
+ Criteria andNameLike(String)
+ Criteria andNameNotLike(String)
+ Criteria andNameIn(List<String>)
+ Criteria andNameNotIn(List<String>)
+ Criteria andNameBetween(String,String)
+ Criteria andNameNotBetween(String,String)
+ Criteria andMailAddressIsNull()
+ Criteria andMailAddressIsNotNull()
+ Criteria andMailAddressEqualTo(String)
+ Criteria andMailAddressNotEqualTo(String)
+ Criteria andMailAddressGreaterThan(String)
+ Criteria andMailAddressGreaterThanOrEqualTo(String)
+ Criteria andMailAddressLessThan(String)
+ Criteria andMailAddressLessThanOrEqualTo(String)
+ Criteria andMailAddressLike(String)
+ Criteria andMailAddressNotLike(String)
+ Criteria andMailAddressIn(List<String>)
+ Criteria andMailAddressNotIn(List<String>)
+ Criteria andMailAddressBetween(String,String)
+ Criteria andMailAddressNotBetween(String,String)
+ Criteria andIsBondIsNull()
+ Criteria andIsBondIsNotNull()
+ Criteria andIsBondEqualTo(BigDecimal)
+ Criteria andIsBondNotEqualTo(BigDecimal)
+ Criteria andIsBondGreaterThan(BigDecimal)
+ Criteria andIsBondGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsBondLessThan(BigDecimal)
+ Criteria andIsBondLessThanOrEqualTo(BigDecimal)
+ Criteria andIsBondIn(List<BigDecimal>)
+ Criteria andIsBondNotIn(List<BigDecimal>)
+ Criteria andIsBondBetween(BigDecimal,BigDecimal)
+ Criteria andIsBondNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedIsNull()
+ Criteria andIsDeletedIsNotNull()
+ Criteria andIsDeletedEqualTo(BigDecimal)
+ Criteria andIsDeletedNotEqualTo(BigDecimal)
+ Criteria andIsDeletedGreaterThan(BigDecimal)
+ Criteria andIsDeletedGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedLessThan(BigDecimal)
+ Criteria andIsDeletedLessThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedIn(List<BigDecimal>)
+ Criteria andIsDeletedNotIn(List<BigDecimal>)
+ Criteria andIsDeletedBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.AdministratorExample.Criteria {
}
class com.evan.seprojrearend.po.AdministratorExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.CourSectionExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.CourSectionExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andSectionIdIsNull()
+ Criteria andSectionIdIsNotNull()
+ Criteria andSectionIdEqualTo(BigDecimal)
+ Criteria andSectionIdNotEqualTo(BigDecimal)
+ Criteria andSectionIdGreaterThan(BigDecimal)
+ Criteria andSectionIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdLessThan(BigDecimal)
+ Criteria andSectionIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdIn(List<BigDecimal>)
+ Criteria andSectionIdNotIn(List<BigDecimal>)
+ Criteria andSectionIdBetween(BigDecimal,BigDecimal)
+ Criteria andSectionIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andTeacherIdIsNull()
+ Criteria andTeacherIdIsNotNull()
+ Criteria andTeacherIdEqualTo(BigDecimal)
+ Criteria andTeacherIdNotEqualTo(BigDecimal)
+ Criteria andTeacherIdGreaterThan(BigDecimal)
+ Criteria andTeacherIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdLessThan(BigDecimal)
+ Criteria andTeacherIdLessThanOrEqualTo(BigDecimal)
+ Criteria andTeacherIdIn(List<BigDecimal>)
+ Criteria andTeacherIdNotIn(List<BigDecimal>)
+ Criteria andTeacherIdBetween(BigDecimal,BigDecimal)
+ Criteria andTeacherIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andCourseIdIsNull()
+ Criteria andCourseIdIsNotNull()
+ Criteria andCourseIdEqualTo(BigDecimal)
+ Criteria andCourseIdNotEqualTo(BigDecimal)
+ Criteria andCourseIdGreaterThan(BigDecimal)
+ Criteria andCourseIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andCourseIdLessThan(BigDecimal)
+ Criteria andCourseIdLessThanOrEqualTo(BigDecimal)
+ Criteria andCourseIdIn(List<BigDecimal>)
+ Criteria andCourseIdNotIn(List<BigDecimal>)
+ Criteria andCourseIdBetween(BigDecimal,BigDecimal)
+ Criteria andCourseIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSectionTimeIsNull()
+ Criteria andSectionTimeIsNotNull()
+ Criteria andSectionTimeEqualTo(String)
+ Criteria andSectionTimeNotEqualTo(String)
+ Criteria andSectionTimeGreaterThan(String)
+ Criteria andSectionTimeGreaterThanOrEqualTo(String)
+ Criteria andSectionTimeLessThan(String)
+ Criteria andSectionTimeLessThanOrEqualTo(String)
+ Criteria andSectionTimeLike(String)
+ Criteria andSectionTimeNotLike(String)
+ Criteria andSectionTimeIn(List<String>)
+ Criteria andSectionTimeNotIn(List<String>)
+ Criteria andSectionTimeBetween(String,String)
+ Criteria andSectionTimeNotBetween(String,String)
+ Criteria andIsCompleteIsNull()
+ Criteria andIsCompleteIsNotNull()
+ Criteria andIsCompleteEqualTo(BigDecimal)
+ Criteria andIsCompleteNotEqualTo(BigDecimal)
+ Criteria andIsCompleteGreaterThan(BigDecimal)
+ Criteria andIsCompleteGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsCompleteLessThan(BigDecimal)
+ Criteria andIsCompleteLessThanOrEqualTo(BigDecimal)
+ Criteria andIsCompleteIn(List<BigDecimal>)
+ Criteria andIsCompleteNotIn(List<BigDecimal>)
+ Criteria andIsCompleteBetween(BigDecimal,BigDecimal)
+ Criteria andIsCompleteNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.CourSectionExample.Criteria {
}
class com.evan.seprojrearend.po.CourSectionExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.SectionInfoExample {
# String orderByClause
# boolean distinct
# List<Criteria> oredCriteria
+ void setOrderByClause(String)
+ String getOrderByClause()
+ void setDistinct(boolean)
+ boolean isDistinct()
+ List<Criteria> getOredCriteria()
+ void or(Criteria)
+ Criteria or()
+ Criteria createCriteria()
# Criteria createCriteriaInternal()
+ void clear()
}
abstract class com.evan.seprojrearend.po.SectionInfoExample.GeneratedCriteria {
# List<Criterion> criteria
+ boolean isValid()
+ List<Criterion> getAllCriteria()
+ List<Criterion> getCriteria()
# void addCriterion(String)
# void addCriterion(String,Object,String)
# void addCriterion(String,Object,Object,String)
+ Criteria andSectionIdIsNull()
+ Criteria andSectionIdIsNotNull()
+ Criteria andSectionIdEqualTo(BigDecimal)
+ Criteria andSectionIdNotEqualTo(BigDecimal)
+ Criteria andSectionIdGreaterThan(BigDecimal)
+ Criteria andSectionIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdLessThan(BigDecimal)
+ Criteria andSectionIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSectionIdIn(List<BigDecimal>)
+ Criteria andSectionIdNotIn(List<BigDecimal>)
+ Criteria andSectionIdBetween(BigDecimal,BigDecimal)
+ Criteria andSectionIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andStudentIdIsNull()
+ Criteria andStudentIdIsNotNull()
+ Criteria andStudentIdEqualTo(BigDecimal)
+ Criteria andStudentIdNotEqualTo(BigDecimal)
+ Criteria andStudentIdGreaterThan(BigDecimal)
+ Criteria andStudentIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andStudentIdLessThan(BigDecimal)
+ Criteria andStudentIdLessThanOrEqualTo(BigDecimal)
+ Criteria andStudentIdIn(List<BigDecimal>)
+ Criteria andStudentIdNotIn(List<BigDecimal>)
+ Criteria andStudentIdBetween(BigDecimal,BigDecimal)
+ Criteria andStudentIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdIsNull()
+ Criteria andSchoolIdIsNotNull()
+ Criteria andSchoolIdEqualTo(BigDecimal)
+ Criteria andSchoolIdNotEqualTo(BigDecimal)
+ Criteria andSchoolIdGreaterThan(BigDecimal)
+ Criteria andSchoolIdGreaterThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdLessThan(BigDecimal)
+ Criteria andSchoolIdLessThanOrEqualTo(BigDecimal)
+ Criteria andSchoolIdIn(List<BigDecimal>)
+ Criteria andSchoolIdNotIn(List<BigDecimal>)
+ Criteria andSchoolIdBetween(BigDecimal,BigDecimal)
+ Criteria andSchoolIdNotBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedIsNull()
+ Criteria andIsDeletedIsNotNull()
+ Criteria andIsDeletedEqualTo(BigDecimal)
+ Criteria andIsDeletedNotEqualTo(BigDecimal)
+ Criteria andIsDeletedGreaterThan(BigDecimal)
+ Criteria andIsDeletedGreaterThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedLessThan(BigDecimal)
+ Criteria andIsDeletedLessThanOrEqualTo(BigDecimal)
+ Criteria andIsDeletedIn(List<BigDecimal>)
+ Criteria andIsDeletedNotIn(List<BigDecimal>)
+ Criteria andIsDeletedBetween(BigDecimal,BigDecimal)
+ Criteria andIsDeletedNotBetween(BigDecimal,BigDecimal)
}
class com.evan.seprojrearend.po.SectionInfoExample.Criteria {
}
class com.evan.seprojrearend.po.SectionInfoExample.Criterion {
- String condition
- Object value
- Object secondValue
- boolean noValue
- boolean singleValue
- boolean betweenValue
- boolean listValue
- String typeHandler
+ String getCondition()
+ Object getValue()
+ Object getSecondValue()
+ boolean isNoValue()
+ boolean isSingleValue()
+ boolean isBetweenValue()
+ boolean isListValue()
+ String getTypeHandler()
}
class com.evan.seprojrearend.po.SysSchoolMesKey {
- String email
- BigDecimal schoolId
+ String getEmail()
+ void setEmail(String)
+ BigDecimal getSchoolId()
+ void setSchoolId(BigDecimal)
}


com.evan.seprojrearend.po.SysUserExample +.. com.evan.seprojrearend.po.SysUserExample.GeneratedCriteria
com.evan.seprojrearend.po.SysUserExample +.. com.evan.seprojrearend.po.SysUserExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.SysUserExample.Criteria
com.evan.seprojrearend.po.SysUserExample +.. com.evan.seprojrearend.po.SysUserExample.Criterion
com.evan.seprojrearend.po.TeacherKey <|-- com.evan.seprojrearend.po.Teacher
com.evan.seprojrearend.po.StudentExample +.. com.evan.seprojrearend.po.StudentExample.GeneratedCriteria
com.evan.seprojrearend.po.StudentExample +.. com.evan.seprojrearend.po.StudentExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.StudentExample.Criteria
com.evan.seprojrearend.po.StudentExample +.. com.evan.seprojrearend.po.StudentExample.Criterion
com.evan.seprojrearend.po.ReportsExample +.. com.evan.seprojrearend.po.ReportsExample.GeneratedCriteria
com.evan.seprojrearend.po.ReportsExample +.. com.evan.seprojrearend.po.ReportsExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.ReportsExample.Criteria
com.evan.seprojrearend.po.ReportsExample +.. com.evan.seprojrearend.po.ReportsExample.Criterion
com.evan.seprojrearend.po.LiteratureKey <|-- com.evan.seprojrearend.po.Literature
com.evan.seprojrearend.po.AdministratorKey <|-- com.evan.seprojrearend.po.Administrator
com.evan.seprojrearend.po.ExperimentKey <|-- com.evan.seprojrearend.po.Experiment
com.evan.seprojrearend.po.CourSectionKey <|-- com.evan.seprojrearend.po.CourSection
com.evan.seprojrearend.po.CourseKey <|-- com.evan.seprojrearend.po.Course
com.evan.seprojrearend.po.LiteratureExample +.. com.evan.seprojrearend.po.LiteratureExample.GeneratedCriteria
com.evan.seprojrearend.po.LiteratureExample +.. com.evan.seprojrearend.po.LiteratureExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.LiteratureExample.Criteria
com.evan.seprojrearend.po.LiteratureExample +.. com.evan.seprojrearend.po.LiteratureExample.Criterion
com.evan.seprojrearend.po.SysSchoolMesExample +.. com.evan.seprojrearend.po.SysSchoolMesExample.GeneratedCriteria
com.evan.seprojrearend.po.SysSchoolMesExample +.. com.evan.seprojrearend.po.SysSchoolMesExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.SysSchoolMesExample.Criteria
com.evan.seprojrearend.po.SysSchoolMesExample +.. com.evan.seprojrearend.po.SysSchoolMesExample.Criterion
com.evan.seprojrearend.po.ExperimentExample +.. com.evan.seprojrearend.po.ExperimentExample.GeneratedCriteria
com.evan.seprojrearend.po.ExperimentExample +.. com.evan.seprojrearend.po.ExperimentExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.ExperimentExample.Criteria
com.evan.seprojrearend.po.ExperimentExample +.. com.evan.seprojrearend.po.ExperimentExample.Criterion
com.evan.seprojrearend.po.SchoolExample +.. com.evan.seprojrearend.po.SchoolExample.GeneratedCriteria
com.evan.seprojrearend.po.SchoolExample +.. com.evan.seprojrearend.po.SchoolExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.SchoolExample.Criteria
com.evan.seprojrearend.po.SchoolExample +.. com.evan.seprojrearend.po.SchoolExample.Criterion
com.evan.seprojrearend.po.ReportsKey <|-- com.evan.seprojrearend.po.Reports
com.evan.seprojrearend.po.TeacherExample +.. com.evan.seprojrearend.po.TeacherExample.GeneratedCriteria
com.evan.seprojrearend.po.TeacherExample +.. com.evan.seprojrearend.po.TeacherExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.TeacherExample.Criteria
com.evan.seprojrearend.po.TeacherExample +.. com.evan.seprojrearend.po.TeacherExample.Criterion
com.evan.seprojrearend.po.ScoreInfoExample +.. com.evan.seprojrearend.po.ScoreInfoExample.GeneratedCriteria
com.evan.seprojrearend.po.ScoreInfoExample +.. com.evan.seprojrearend.po.ScoreInfoExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.ScoreInfoExample.Criteria
com.evan.seprojrearend.po.ScoreInfoExample +.. com.evan.seprojrearend.po.ScoreInfoExample.Criterion
com.evan.seprojrearend.po.SectionInfoKey <|-- com.evan.seprojrearend.po.SectionInfo
com.evan.seprojrearend.po.ScoreInfoKey <|-- com.evan.seprojrearend.po.ScoreInfo
com.evan.seprojrearend.po.SectionMessageExample +.. com.evan.seprojrearend.po.SectionMessageExample.GeneratedCriteria
com.evan.seprojrearend.po.SectionMessageExample +.. com.evan.seprojrearend.po.SectionMessageExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.SectionMessageExample.Criteria
com.evan.seprojrearend.po.SectionMessageExample +.. com.evan.seprojrearend.po.SectionMessageExample.Criterion
com.evan.seprojrearend.po.CourseExample +.. com.evan.seprojrearend.po.CourseExample.GeneratedCriteria
com.evan.seprojrearend.po.CourseExample +.. com.evan.seprojrearend.po.CourseExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.CourseExample.Criteria
com.evan.seprojrearend.po.CourseExample +.. com.evan.seprojrearend.po.CourseExample.Criterion
com.evan.seprojrearend.po.StudentKey <|-- com.evan.seprojrearend.po.Student
com.evan.seprojrearend.po.AdministratorExample +.. com.evan.seprojrearend.po.AdministratorExample.GeneratedCriteria
com.evan.seprojrearend.po.AdministratorExample +.. com.evan.seprojrearend.po.AdministratorExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.AdministratorExample.Criteria
com.evan.seprojrearend.po.AdministratorExample +.. com.evan.seprojrearend.po.AdministratorExample.Criterion
com.evan.seprojrearend.po.CourSectionExample +.. com.evan.seprojrearend.po.CourSectionExample.GeneratedCriteria
com.evan.seprojrearend.po.CourSectionExample +.. com.evan.seprojrearend.po.CourSectionExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.CourSectionExample.Criteria
com.evan.seprojrearend.po.CourSectionExample +.. com.evan.seprojrearend.po.CourSectionExample.Criterion
com.evan.seprojrearend.po.SectionInfoExample +.. com.evan.seprojrearend.po.SectionInfoExample.GeneratedCriteria
com.evan.seprojrearend.po.SectionInfoExample +.. com.evan.seprojrearend.po.SectionInfoExample.Criteria
com.evan.seprojrearend.po.GeneratedCriteria <|-- com.evan.seprojrearend.po.SectionInfoExample.Criteria
com.evan.seprojrearend.po.SectionInfoExample +.. com.evan.seprojrearend.po.SectionInfoExample.Criterion
@enduml